### ISSUE TITLE
Support double jump

### ISSUE THREAD

**Issue by VincentDouchin** [idanarye/bevy-tnua#23]
We should be able to allow the player to jump again while in the air. The number of possible jumps while in the air should be configurable via the TnuaPlatformerConfig and via the TnuaPlatformerControls in order to give the player another jump if picking up an item for example. 
I just noticed this is mentionned in #6, my bad! this issue can be closed

**Comment by idanarye** [comment]
Let's keep it open, actually. It may be beneficial to split this into "do things other than jumps" and "start things in mid-air".
