### ISSUE TITLE
LockedAxis

### ISSUE THREAD

**Issue by CMorrison82z** [idanarye/bevy-tnua#29]
Docs mention a way for locking the tilt of a character (rigidly align the body with `up`), but I can't actually find any component or properties to achieve this.

**Comment by idanarye** [comment]
This is not done in Tnua. This is done in the physics backend - e.g. if you are using bevy_rapier3d, you need  the [`LockedAxes`](https://docs.rs/bevy_rapier3d/latest/bevy_rapier3d/dynamics/struct.LockedAxes.html) component.

I'll amend the docs to make this more clear.
