### ISSUE TITLE
Expose or add certain methods for ease of use outside of a TnuaAction implementation

### ISSUE THREAD

**Issue by Microwonk** [idanarye/bevy-tnua#31]
For example wanting to see if a player is grounded in this example:

```
if dash {
            if keyboard.pressed(KeyConfig::DOWN) {
                direction -= Vec3::Y;
            }
            if keyboard.pressed(KeyConfig::UP) {
                direction += Vec3::Y;
            }

            let mut needs_inf = direction.y < 0.;
             // want to check if the player is on ground during the dash here
            needs_inf |= !controller.context.is_airborne(); // as an example

            controller.action(TnuaBuiltinDash {
                displacement: direction.normalize_or_zero() * config.dash_distance,
                allow_in_air: air_actions_counter.air_count_for(TnuaBuiltinDash::NAME)
                    <= config.actions_in_air,
                brake_to_speed: if needs_inf {
                    // needs to be set to infinity, so there is no braking force being applied when gravity is active or dash is on ground
                    f32::INFINITY
                } else {
                    config.dash.brake_to_speed
                },
                ..config.dash.clone()
            });
}
```
Correct me if im wrong or if there is a better way that is already available to check for this.

**Comment by idanarye** [comment]
The decision of whether the character is airborne [is made by the basis](https://docs.rs/bevy-tnua/0.13.0/bevy_tnua/trait.TnuaBasis.html#tymethod.is_airborne). Right now `TnuaBuiltinWalk` is the only basis, but in the future I'll want to add more (climb? swim?) which will make their own airbornness decisions.

You can get that information out of the basis by using a dynamic handle to the basis:

```rust
let is_airborne = controller.dynamic_basis().unwrap().is_airborne();
```

I've noticed that for some reason `DynamicBasis` is not exposed. It's `pub`, but not reachable from outside the crate so it does not appear in the docs. I'll fix that.

Note that `dynamic_basis()` will return `None` if you call it before setting the basis for the first time. If this is a problem, you should decide on a default value for this.

Also note that if the character is in the air but during coyote time, `is_airborne` will return `false`. This is usually the desired behavior - this is what coyote time is for! - but if for whatever reason it isn't you'll have to figure out if the character is airborne via some other means - typically by looking at the proximity sensor's output, but you may also want to check the active action and figure if you want to consider the character airborne when this action is active. Maybe even look at the action's state.

**Comment by idanarye** [comment]
Would it be better if I added `controller.is_airborne()`? It'll return `Option<bool>` (in case the basis is empty), but it'll be easier to set a default that way (`controller.is_airborne().unwrap_or(true)`)

**Comment by Microwonk** [comment]
I think that would be a great addition. I looked into the source code and did eventually stumble upon the way you described to do it. The `controller.is_airborne()` would definitely be a nice quality of life improvement!

**Comment by Microwonk** [comment]
The abstraction would probably make sense as instead of writing this:

```rust
let airborne = match controller.dynamic_basis() {
    Some(basis) => basis.is_airborne(),
    None => false,
};
```

it would be a bit simpler. Not necessary at all but a QOL improvement.
