### ISSUE TITLE
Potential f64 support

### ISSUE THREAD

**Issue by vpochapuis** [idanarye/bevy-tnua#46]
Hello!
Thank you for providing a character controller crate!
After seeing this crate for the first time and trying to integrate with a bevy/xpbd setup I had, i came to encounter some compilation issues and found that it seems the crate used `f32` as default from xpbd and rapier.
Hence I was wondering about this issue:

# What

As both Rapier and XPBD provide `f64` precision alternative features(xpbd)/crates([rapier](https://crates.io/crates/rapier2d-f64)). Would it be possible  to adapt this crate to take advantages of those?

# Why

- Higher simulation precision
- Prevent rounding errors due to f32
- ...

**Comment by idanarye** [comment]
Rapier has an `f64` version, but bevy_rapier doesn't. bevy_xpbd (which is the main XPBD crate) does support it, so it is possible for XPBD.
