### ISSUE TITLE
Setting XPBD Gravity resource to 0 and my character still falls ?

### ISSUE THREAD

**Issue by ethereumdegen** [idanarye/bevy-tnua#48]
Setting XPBD Gravity resource to 0 and my character still falls ?

**Comment by idanarye** [comment]
There are several things in Tuna that can generate downward acceleration/impulses even when you set the gravity to 0, but if I had to guess - I'd say it's [`free_fall_extra_gravity`](https://docs.rs/bevy-tnua/0.15.0/bevy_tnua/builtins/struct.TnuaBuiltinWalk.html#structfield.free_fall_extra_gravity). Try setting it to 0 (at least when you disable gravity)

Also, if you are using [`TnuaBuiltinJump`](https://docs.rs/bevy-tnua/0.15.0/bevy_tnua/builtins/struct.TnuaBuiltinJump.html), notice that it also has several fields that end with `_extra_gravity`, so maybe you'll have to zero them as well.

**Comment by ethereumdegen** [comment]
i fixed this for now  by pausing physics time when i need to prevent falling (like when world is loading)

**Comment by ethereumdegen** [comment]
BUT it would be cool to have a 'flying' builtin
