### ISSUE TITLE
Add an example / best practices for climbing (ladder / ivy)

### ISSUE THREAD

**Issue by ethereumdegen** [idanarye/bevy-tnua#54]
Add an example / best practices for climbing (ladder / ivy)

**Comment by idanarye** [comment]
It's not supported yet (though I do plan to support it). One could hack it with a custom Basis/Action, of course, but they'd pretty much be implementing the whole thing from scratch, which is not something I want to put in an official example.

Once I support the feature I'll create an example.

**Comment by ethereumdegen** [comment]
I am trying to implement this custom Climbing basis myself (forking the Walk one),  and i also want to implement NoClip flying like in SourceEngine games. 

However, to do this, I would like my custom basis to be able to have a trait that lets me turn off collision and turn off gravity some how.  This would be nice for Swimming too.  Does that make sense?  How can i do that?  (is there a hacky work around for now ?)

**Comment by ethereumdegen** [comment]
Okay i realized i can use Avian3d GravityScale component to do the gravity scaling.  However how can I 

1) control VELOCITY of climbing a ladder, not only acceleration as it seems i can only do now in the basis?  
2) disable collision for my character while i am climbing the ladder?

**Comment by ethereumdegen** [comment]
Oh i think i can use LinearDamping and LockedAxes ... will report back :P

**Comment by idanarye** [comment]
[`TnuaVelChange`](https://docs.rs/bevy-tnua/0.19.0/bevy_tnua/data_for_backends/struct.TnuaVelChange.html) (which [`TnuaMotor`](https://docs.rs/bevy-tnua/0.19.0/bevy_tnua/data_for_backends/struct.TnuaMotor.html) uses for both linear and angular movement) has both `boost` and `acceleration` fields. You can use `boost` to cancel existing velocity and `acceleration` to offset the gravity - and then add on top of that the boost and/or acceleration you actually want the character to have.

As for determining what you need to cancel - [`TnuaBasisContext`](https://docs.rs/bevy-tnua/0.19.0/bevy_tnua/struct.TnuaBasisContext.html) (which you get as a parameter in `apply`) has a [`tracker`](https://docs.rs/bevy-tnua/0.19.0/bevy_tnua/data_for_backends/struct.TnuaRigidBodyTracker.html) field with that information.

**Comment by ethereumdegen** [comment]
ahh okay.  I think it is a bit weird that i have to cancel out gravity in the basis code and that it is automatically applied.   Since i am making a NoClip basis and Floating basis and Swimming basis, it is super annoying to have to deal with the fact that gravity is implicitly applied and then having to cancel it out.  I would rather gravity NOT be implicitly applied and then i would just need to apply it myself in the basis that use gravity like Walk and Crouch and what not ... hmm ..

**Comment by ethereumdegen** [comment]
IM trying to counteract gravity like you describe but it isnt working ..


```
 let grav =  ctx.tracker
                        .gravity
                         
                        * ctx.frame_duration;
 

        let anti_gravity = -1.0  * grav;

        motor.lin =   TnuaVelChange {
            boost: vertical_velocity_boost,
            acceleration: anti_gravity
        } ; //+ upward_impulse;
        
```

**Comment by idanarye** [comment]
Weird. I'll have to look into it.

**Comment by idanarye** [comment]
> Since i am making a NoClip basis

Not sure this is possible with just Tnua. A no-clip requires interfering with the physics backend's collision configuration, which Tnua doesn't do. This is part of the root of many of the limitations you encounter - I'm trying to limit the surface area between Tnua and the physics backend, to reduce the effort it requires to support all the different backends.

**Comment by ethereumdegen** [comment]
i implemented ladder climbing by locking axes of motion for the entity in the phys engine.
